### PR TITLE
Four new exercises with solution in Java added.

### PR DESCRIPTION
**Pull request by AntonioRedondo**
Hi there,

I just added four new exercises with the solution implemented in Java.

Antonio

### CODE REVIEW

**Comment by blakeembrey** [comment]
@AntonioRedondo Thanks for the contributions! Can you add some sources to the problems? My only issue is that (at least one) looks very similar to problems I've done before but DCMA take down for since it violated the copyright of the original site. Aside from that, do we have a better name than `Game of Life`? Seems like it could be confused with Conway's.

**Comment by AntonioRedondo** [comment]
Hi @blakeembrey. The source is the companies which I did the interview for. Though if you think they are potentially not the original source discard the affected problems from the commit.

Regarding the 'Game Of Life' problem, indeed it is called like this because it pretends to resemble a simplified version of Conway's invention, but I guess it's so oversimplified that losses its meaning. Perhaps a better name may be 'Binary Matrix'.

**Comment by blakeembrey** [comment]
Wait, isn't "Game of Life" currently the stack machine problem?

**Comment by AntonioRedondo** [comment]
Oh yeah, the first line of the `md` file for the Stack Machine problem is wrong. It should be 'Stack Machine'. Sorry about the confusion, I'm working locally with a 'Game Of Life' problem, so from there was coming the misunderstand.

**Comment by blakeembrey** [comment]
@AntonioRedondo Could you correct name? I think it's alright to merge after that, but I'll look a little more.

**Comment by AntonioRedondo** [comment]
Done. :)

**Pull request merged**
