### PR TITLE
Create closetsum.py

### PR DESCRIPTION
**Pull request by pkmm91**
python code to find the elements in a list whose sum is closest to given value.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@pkmm91 Did you want to add a problem text for this? I don't think one exists.

**Comment by pkmm91** [comment]
Yes, i will add.

**Comment by blakeembrey** [comment]
Thank you. Just make a comment when it's added and I'll look again.

**Comment by pkmm91** [comment]
Added the problem statement, plz check.

**Comment by blakeembrey** [comment]
I merged it with master.

**Pull request closed without merging**
