### PR TITLE
Add new problem: The Queen threatens the King

### PR DESCRIPTION
**Pull request by mmrko**
Thanks for this awesome repo :) Thought I'd share a coding challenge I came across in an interview recently. Added initial solution in JavaScript.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Awesome :+1:

**Comment by jmera** [comment]
Cool problem :+1: I'm going to hack on this one. Thanks @mmrko

**Comment by mmrko** [comment]
Thanks @jmera I'm glad to hear that :) kudos to @blakeembrey for this neat resource!

**Comment by jmera** [comment]
@mmrko when the king and the queen are on the same square (i.e., `king_x == queen_x && king_y == queen_y`), shouldn't the function raise an error or return false?  Two pieces aren't allowed to occupy the same space in Chess.

Or, we could just assume that our function parameters will always be valid, then include that assumption in the problem description.

**Comment by mmrko** [comment]
Yeah, I missed that, thanks! Returning false SGTM.

**Pull request merged**
