### PR TITLE
Widea - Added solution to treelevelorderprint

### PR DESCRIPTION
**Pull request by Widea**

### CODE REVIEW

**Comment by blakeembrey** [comment]
@Widea Should `treelevelorderprint` have a `.java` extension?

**Comment by Widea** [comment]
@blakeembrey : Yes, since the program has its own main class, a .java extension is required.

**Comment by blakeembrey** [comment]
@Widea It's missing right now, that was what I meant - sorry :smile:

**Comment by Widea** [comment]
aah! Now I get it. Missed it! :P

**Comment by blakeembrey** [comment]
Awesome, thanks :+1:

**Pull request merged**
